### ISSUE TITLE
SSH private key read with ?ssh-format=openssh causes ^M (DOS/Windows line-ending)

### ISSUE THREAD

**Issue by Japje** [1Password/load-secrets-action#59] opened 2023-12-06 16:00 UTC
When using op to get an SSH private key and use it for CI/CD purposes i ran into this issue.

`op read "op://some-vault/some-entry/private key?ssh-format=openssh" > /tmp/key.txt`

there are windows line endings

```
$ grep -r $'\r' /tmp/key.txt 
-----BEGIN OPENSSH PRIVATE KEY-----
lz+m8YgbS6fn/D+URRBMAAAAAAECAwQF
-----END OPENSSH PRIVATE KEY-----
```

![image](https://github.com/1Password/load-secrets-action/assets/1974315/fec3b172-f998-4281-ad46-6e9d885afa6c)

When trying to load the key this will result in an error
`Load key "/tmp/key.txt": error in libcrypto`

removing the line endings with dos2unix or `tr -d '\r'` fixes this.

**Comment by SimonBarendse** [comment] 2024-11-13 22:32
Thanks @bartekpacia ! That indeed seems like that was the root cause of this.

I'm going to close this ticket as solved, but please let us know if you're still running into this after [that CLI fix](https://app-updates.agilebits.com/product_history/CLI2#v2250101) and we can re-open to investigate further.

**Closed by SimonBarendse** 2024-11-13 22:32 UTC
